#pragma once

// From glfw3.h
#define FISH_MOUSE_BUTTON_1         0
#define FISH_MOUSE_BUTTON_2         1
#define FISH_MOUSE_BUTTON_3         2
#define FISH_MOUSE_BUTTON_4         3
#define FISH_MOUSE_BUTTON_5         4
#define FISH_MOUSE_BUTTON_6         5
#define FISH_MOUSE_BUTTON_7         6
#define FISH_MOUSE_BUTTON_8         7
#define FISH_MOUSE_BUTTON_LAST      FISH_MOUSE_BUTTON_8
#define FISH_MOUSE_BUTTON_LEFT      FISH_MOUSE_BUTTON_1
#define FISH_MOUSE_BUTTON_RIGHT     FISH_MOUSE_BUTTON_2
#define FISH_MOUSE_BUTTON_MIDDLE    FISH_MOUSE_BUTTON_3
